// Generated by gencpp from file simple_arm/GoToPositionRequest.msg
// DO NOT EDIT!


#ifndef SIMPLE_ARM_MESSAGE_GOTOPOSITIONREQUEST_H
#define SIMPLE_ARM_MESSAGE_GOTOPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simple_arm
{
template <class ContainerAllocator>
struct GoToPositionRequest_
{
  typedef GoToPositionRequest_<ContainerAllocator> Type;

  GoToPositionRequest_()
    : joint_1(0.0)
    , joint_2(0.0)  {
    }
  GoToPositionRequest_(const ContainerAllocator& _alloc)
    : joint_1(0.0)
    , joint_2(0.0)  {
  (void)_alloc;
    }



   typedef double _joint_1_type;
  _joint_1_type joint_1;

   typedef double _joint_2_type;
  _joint_2_type joint_2;





  typedef boost::shared_ptr< ::simple_arm::GoToPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_arm::GoToPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GoToPositionRequest_

typedef ::simple_arm::GoToPositionRequest_<std::allocator<void> > GoToPositionRequest;

typedef boost::shared_ptr< ::simple_arm::GoToPositionRequest > GoToPositionRequestPtr;
typedef boost::shared_ptr< ::simple_arm::GoToPositionRequest const> GoToPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_arm::GoToPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_arm::GoToPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simple_arm::GoToPositionRequest_<ContainerAllocator1> & lhs, const ::simple_arm::GoToPositionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joint_1 == rhs.joint_1 &&
    lhs.joint_2 == rhs.joint_2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simple_arm::GoToPositionRequest_<ContainerAllocator1> & lhs, const ::simple_arm::GoToPositionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simple_arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::simple_arm::GoToPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_arm::GoToPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_arm::GoToPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_arm::GoToPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_arm::GoToPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_arm::GoToPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_arm::GoToPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "243293dc5d540de7ec323fc657126846";
  }

  static const char* value(const ::simple_arm::GoToPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x243293dc5d540de7ULL;
  static const uint64_t static_value2 = 0xec323fc657126846ULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_arm::GoToPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_arm/GoToPositionRequest";
  }

  static const char* value(const ::simple_arm::GoToPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_arm::GoToPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 joint_1\n"
"float64 joint_2\n"
;
  }

  static const char* value(const ::simple_arm::GoToPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_arm::GoToPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_1);
      stream.next(m.joint_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_arm::GoToPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_arm::GoToPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_1: ";
    Printer<double>::stream(s, indent + "  ", v.joint_1);
    s << indent << "joint_2: ";
    Printer<double>::stream(s, indent + "  ", v.joint_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_ARM_MESSAGE_GOTOPOSITIONREQUEST_H
