// Generated by gencpp from file simple_arm/GoToPosition.msg
// DO NOT EDIT!


#ifndef SIMPLE_ARM_MESSAGE_GOTOPOSITION_H
#define SIMPLE_ARM_MESSAGE_GOTOPOSITION_H

#include <ros/service_traits.h>


#include <simple_arm/GoToPositionRequest.h>
#include <simple_arm/GoToPositionResponse.h>


namespace simple_arm
{

struct GoToPosition
{

typedef GoToPositionRequest Request;
typedef GoToPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToPosition
} // namespace simple_arm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simple_arm::GoToPosition > {
  static const char* value()
  {
    return "fc4e1ffd0bd5c9cc8c021e351562f1a8";
  }

  static const char* value(const ::simple_arm::GoToPosition&) { return value(); }
};

template<>
struct DataType< ::simple_arm::GoToPosition > {
  static const char* value()
  {
    return "simple_arm/GoToPosition";
  }

  static const char* value(const ::simple_arm::GoToPosition&) { return value(); }
};


// service_traits::MD5Sum< ::simple_arm::GoToPositionRequest> should match
// service_traits::MD5Sum< ::simple_arm::GoToPosition >
template<>
struct MD5Sum< ::simple_arm::GoToPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simple_arm::GoToPosition >::value();
  }
  static const char* value(const ::simple_arm::GoToPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_arm::GoToPositionRequest> should match
// service_traits::DataType< ::simple_arm::GoToPosition >
template<>
struct DataType< ::simple_arm::GoToPositionRequest>
{
  static const char* value()
  {
    return DataType< ::simple_arm::GoToPosition >::value();
  }
  static const char* value(const ::simple_arm::GoToPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simple_arm::GoToPositionResponse> should match
// service_traits::MD5Sum< ::simple_arm::GoToPosition >
template<>
struct MD5Sum< ::simple_arm::GoToPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simple_arm::GoToPosition >::value();
  }
  static const char* value(const ::simple_arm::GoToPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_arm::GoToPositionResponse> should match
// service_traits::DataType< ::simple_arm::GoToPosition >
template<>
struct DataType< ::simple_arm::GoToPositionResponse>
{
  static const char* value()
  {
    return DataType< ::simple_arm::GoToPosition >::value();
  }
  static const char* value(const ::simple_arm::GoToPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMPLE_ARM_MESSAGE_GOTOPOSITION_H
